help:
	@echo make install
	@echo make run-api
	@echo make run-ui
	@echo make run
	@echo make test
	@echo make clean

install:
	yarn install

run-api:
	yarn mock:api

run-ui:
	yarn start

run:
	yarn dev

test:
	yarn test

clean:
	rm -fr ./node_modules
