help:
	@echo make install
	@echo make start
	@echo make dev
	@echo make clean

install:
	# npm install
	yarn install

run-ui:
	yarn start

run-api:
	yarn mock:api

dev:
	yarn dev

clean:
	rm -fr ./node_modules






