# Generated by Django 3.1.3 on 2020-11-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0003_timeline_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeline',
            new_name='Observation',
        ),
    ]
