# Generated by Django 3.1.3 on 2020-11-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0004_auto_20201124_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snobird_v7.patient'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snobird_v7.patient'),
        ),
    ]
