# Generated by Django 3.1.3 on 2020-11-25 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0005_auto_20201124_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='patient_relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snobird_v7.patient'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='patient',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
