# Generated by Django 3.1.3 on 2020-11-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0006_auto_20201124_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='patient_relationship',
            new_name='patient_id',
        ),
    ]
