# Generated by Django 3.1.3 on 2020-11-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0007_auto_20201124_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='patient_id',
        ),
    ]
