# Generated by Django 3.1.3 on 2020-12-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0009_auto_20201201_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='type_cd',
            field=models.IntegerField(null=True),
        ),
    ]
