# Generated by Django 3.1.3 on 2020-12-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0011_remove_observation_type_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='type_cd',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
