# Generated by Django 3.1.3 on 2020-12-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0012_observation_type_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='type_cd',
            field=models.IntegerField(null=True),
        ),
    ]
