# Generated by Django 3.1.3 on 2020-12-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0014_auto_20201203_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
