# Generated by Django 3.1.3 on 2021-02-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0018_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='project',
            field=models.ManyToManyField(to='snobird_v7.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='researcher',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
