# Generated by Django 3.1.3 on 2021-02-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0022_auto_20210203_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientoption',
            name='patient_option_details',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
