# Generated by Django 3.1.3 on 2021-02-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0023_auto_20210208_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientoption',
            name='patient_option_details',
            field=models.JSONField(default='dict()'),
        ),
    ]
