# Generated by Django 3.1.3 on 2020-11-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('name', 'time_stamp'),
            },
        ),
    ]
