help:

	@echo make install
	@echo make start
	@echo make run-apis
	@echo make dev
	@echo make clean

install:

	yarn install

start:
	yarn start

run-apis:

	yarn mock:api


dev:
	 yarn dev

clean:
	 rm -fr ./node_modules

