# Generated by Django 3.1.2 on 2020-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('birth_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField(auto_now_add=True, null=True)),
                ('form', models.CharField(choices=[('Form', 'Form'), ('Tablet', 'Tablet'), ('Powder', 'Powder'), ('Capsule', 'Capsule')], max_length=10, null=True)),
                ('amount', models.CharField(max_length=3, null=True)),
                ('patient', models.ManyToManyField(to='main.Patient')),
            ],
        ),
    ]
