# Generated by Django 3.1.2 on 2020-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField()),
                ('form', models.CharField(choices=[('P', 'P'), ('T', 'T'), ('C', 'C')], max_length=1)),
                ('amount', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=5)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
