# Generated by Django 3.1.2 on 2020-10-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_medication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='amount',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
