# Generated by Django 3.1.2 on 2020-11-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='heart_rate',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='patient',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
