# Generated by Django 3.1.2 on 2020-11-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snobird_v7', '0002_auto_20201112_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
