# Generated by Django 3.1.2 on 2020-10-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_timeline_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
